name: Build and publish python package

on:
  release:
    types: [ published ]

jobs:
    Release:
      runs-on: ubuntu-latest
      #needs: test
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry==1.5.0
      - uses: bjoluc/semantic-release-config-poetry@v2
        with:
          pypi_token: ${{ secrets.PUBLISH_REGISTRY_PASSWORD }}
          PYPI_REPOSITORY: "https://test.pypi.org/legacy/"
